name: stadtnavi_app
description: A Flutter Application for the Stadtnavi Herrenberg
repository: https://github.com/stadtnavi/stadtnavi-app
homepage: https://stadtnavi.de/
issue_tracker: https://github.com/stadtnavi/stadtnavi-app/issues

publish_to: 'none'

version: 1.0.2+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  global_configuration: ^2.0.0-nullsafety.1
  lint: ^1.5.3
# TODO: improve the trufi_core dependency, e.g use tags instead commits
# the ref should not be a branch because the `pub get` will not get the latest change
# so the ref is refering to the latest commit
  trufi_core:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: 39249d0bd80d20dcc8df20600ab7709ba06ee069


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/data/
    - assets/data/hb-layers/
    - assets/images/