name: stadtnavi_app
description: A Flutter Application for the Stadtnavi Herrenberg
repository: https://github.com/stadtnavi/stadtnavi-app
homepage: https://stadtnavi.de/
issue_tracker: https://github.com/stadtnavi/stadtnavi-app/issues

publish_to: 'none'

version: 1.0.4+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3

  flutter:
    sdk: flutter

  lint: ^1.5.3

  # TODO: improve the trufi_core dependency, e.g use tags instead commits
  # the ref should not be a branch because the `pub get` will not get the latest change
  # so the ref is refering to the latest commit
  trufi_core:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: 5ce524a8da13a38f86fee8ad356ad0a41c37355e


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/data/
    - assets/data/hb-layers/
    - assets/images/